import { Product, Category, Order, UserProfile } from "@/types";

// ─── Categories ──────────────────────────────────────────────────────────────
export const categories: Category[] = [
  { id: "cat-1", name: "Sofa & Lounge", slug: "sofa-lounge", room: "Ruang Tamu", productCount: 18 },
  { id: "cat-2", name: "Kursi Aksen", slug: "kursi-aksen", room: "Ruang Tamu", productCount: 12 },
  { id: "cat-3", name: "Meja Kopi & Samping", slug: "meja-kopi-samping", room: "Ruang Tamu", productCount: 10 },
  { id: "cat-4", name: "Credenza & Konsol", slug: "credenza-konsol", room: "Ruang Tamu", productCount: 8 },
  { id: "cat-5", name: "Tempat Tidur", slug: "tempat-tidur", room: "Kamar Tidur", productCount: 6 },
  { id: "cat-6", name: "Meja Makan", slug: "meja-makan", room: "Ruang Makan", productCount: 7 },
  { id: "cat-7", name: "Kursi Makan", slug: "kursi-makan", room: "Ruang Makan", productCount: 9 },
  { id: "cat-8", name: "Meja Kerja", slug: "meja-kerja", room: "Ruang Kerja", productCount: 5 },
  { id: "cat-9", name: "Pencahayaan", slug: "pencahayaan", room: "Pencahayaan", productCount: 8 },
  { id: "cat-10", name: "Dekorasi", slug: "dekorasi", room: "Dekorasi", productCount: 6 },
];

// ─── Products ────────────────────────────────────────────────────────────────
export const products: Product[] = [
  {
    id: "prod-1",
    name: "Astra Minimalist Armchair",
    slug: "astra-minimalist-armchair",
    description: "Astra Minimalist Armchair adalah perwujudan sejati dari estetika Zen kontemporer. Dibuat dengan presisi tinggi oleh pengrajin lokal berbakat di Jepara, kursi aksen ini memadukan kehangatan serat kayu jati solid dengan tekstur kain bouclé premium yang mewah namun bersahaja.\n\nSetiap kurva dirancang secara ergonomis untuk memberikan pelukan hangat saat Anda menikmati waktu membaca atau secangkir kopi di pagi hari. Desainnya yang timeless memastikan kursi ini menjadi focal point yang memukau di ruang tamu, sudut kamar tidur, atau ruang kerja pribadi Anda.",
    price: 4850000,
    material: "Kayu Jati Solid, Linen Premium",
    status: "Ready Stock",
    rating: 4.9,
    reviewCount: 48,
    dimensions: { panjang: 85, lebar: 82, tinggi: 78 },
    attributes: {
      seatHeight: "42 cm dari lantai, proporsional untuk kenyamanan bersantai maupun membaca.",
      cushionDensity: "Lapisan busa HR (High Resilience) dipadu dacron lembut untuk keempukan yang tahan lama.",
      frameConstruction: "Kayu Jati Perhutani pilihan dengan sistem mortise & tenon joint yang kokoh.",
    },
    categoryId: "cat-2",
    categoryName: "Kursi Aksen",
    room: "Ruang Tamu",
    images: [
      { id: "img-1-1", url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80", altText: "Astra Minimalist Armchair tampak depan", sortOrder: 0 },
      { id: "img-1-2", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80", altText: "Astra Minimalist Armchair tampak samping", sortOrder: 1 },
      { id: "img-1-3", url: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80", altText: "Astra Minimalist Armchair detail kayu", sortOrder: 2 },
      { id: "img-1-4", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80", altText: "Astra Minimalist Armchair di ruangan", sortOrder: 3 },
    ],
    variants: [
      { id: "var-1-1", productId: "prod-1", type: "material_kayu", label: "Jati Natural", hexOrSwatch: "#8B6914", priceOffset: 0, stock: 15 },
      { id: "var-1-2", productId: "prod-1", type: "material_kayu", label: "Jati Walnut", hexOrSwatch: "#5C4033", priceOffset: 200000, stock: 8 },
      { id: "var-1-3", productId: "prod-1", type: "material_kayu", label: "Jati Honey", hexOrSwatch: "#C8A951", priceOffset: 150000, stock: 5 },
      { id: "var-1-4", productId: "prod-1", type: "warna_kain", label: "Oatmeal Bouclé", hexOrSwatch: "#E8DFD0", priceOffset: 0, stock: 20 },
      { id: "var-1-5", productId: "prod-1", type: "warna_kain", label: "Sage Linen", hexOrSwatch: "#B2BDA0", priceOffset: 0, stock: 12 },
      { id: "var-1-6", productId: "prod-1", type: "warna_kain", label: "Charcoal Woven", hexOrSwatch: "#4A4A4A", priceOffset: 100000, stock: 10 },
    ],
    colorSwatches: ["#8B6914", "#5C4033", "#E8DFD0", "#4A4A4A"],
    isFeatured: true,
  },
  {
    id: "prod-2",
    name: "Elva Lounge Chair",
    slug: "elva-lounge-chair",
    description: "Elva Lounge Chair menggabungkan keanggunan rotan alami dengan kenyamanan modern. Rangka rotan yang dilengkungkan secara manual memberikan karakter unik pada setiap unit. Bantal duduk empuk dengan busa high-density memastikan kenyamanan optimal untuk bersantai berjam-jam.",
    price: 4750000,
    material: "Kayu Jati Padat, Rotan Alami",
    status: "Ready Stock",
    statusDetail: "Ready Stock",
    rating: 4.7,
    reviewCount: 32,
    dimensions: { panjang: 75, lebar: 78, tinggi: 80 },
    attributes: {
      seatHeight: "40 cm",
      cushionDensity: "Busa HD + dacron wrap",
      frameConstruction: "Kayu jati + anyaman rotan tangan",
    },
    categoryId: "cat-2",
    categoryName: "Kursi Aksen",
    room: "Ruang Tamu",
    images: [
      { id: "img-2-1", url: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80", altText: "Elva Lounge Chair", sortOrder: 0 },
      { id: "img-2-2", url: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&q=80", altText: "Elva Lounge Chair side view", sortOrder: 1 },
    ],
    variants: [
      { id: "var-2-1", productId: "prod-2", type: "material_kayu", label: "Jati Natural", hexOrSwatch: "#8B6914", priceOffset: 0, stock: 10 },
      { id: "var-2-2", productId: "prod-2", type: "material_kayu", label: "Rotan Honey", hexOrSwatch: "#C8A951", priceOffset: 0, stock: 12 },
    ],
    colorSwatches: ["#8B6914", "#C8A951"],
    isFeatured: true,
  },
  {
    id: "prod-3",
    name: "Kala Organic Coffee Table",
    slug: "kala-organic-coffee-table",
    description: "Meja kopi organik Kala menampilkan keindahan alami serat kayu oak Eropa dalam bentuk yang minimalis. Setiap meja dibuat dari satu potongan kayu solid, menampilkan pola serat yang unik dan tak terulang. Finishing natural matte melindungi kayu sekaligus menonjolkan karakter alaminya.",
    price: 6200000,
    material: "Solid European Oak",
    status: "Ready Stock",
    rating: 4.8,
    reviewCount: 27,
    dimensions: { panjang: 120, lebar: 60, tinggi: 42 },
    attributes: {
      finish: "Natural Matte Oil",
      frameConstruction: "Solid oak, mortise & tenon joints",
    },
    categoryId: "cat-3",
    categoryName: "Meja Kopi & Samping",
    room: "Ruang Tamu",
    images: [
      { id: "img-3-1", url: "https://images.unsplash.com/photo-1634712282287-14ed57b9cc89?w=800&q=80", altText: "Kala Organic Coffee Table", sortOrder: 0 },
      { id: "img-3-2", url: "https://images.unsplash.com/photo-1611967164521-abae8fba4668?w=800&q=80", altText: "Kala Coffee Table detail", sortOrder: 1 },
    ],
    variants: [
      { id: "var-3-1", productId: "prod-3", type: "material_kayu", label: "Oak Natural", hexOrSwatch: "#C4A35A", priceOffset: 0, stock: 7 },
      { id: "var-3-2", productId: "prod-3", type: "material_kayu", label: "Oak Smoked", hexOrSwatch: "#5C4033", priceOffset: 300000, stock: 4 },
    ],
    colorSwatches: ["#C4A35A", "#5C4033"],
    isFeatured: true,
  },
  {
    id: "prod-4",
    name: "Lumina Brass Floor Lamp",
    slug: "lumina-brass-floor-lamp",
    description: "Lampu lantai Lumina Brass menggabungkan keanggunan tiang kuningan yang dipatri secara manual dengan kepala lampu kain organik yang memancarkan cahaya hangat dan merata. Cocok sebagai pencahayaan ambient di sudut ruang tamu atau sebagai lampu baca di samping kursi favorit Anda.",
    price: 2950000,
    material: "Teak & Organic Linen Shade",
    status: "Pre-Order",
    statusDetail: "Pre-Order (3 Minggu)",
    rating: 4.6,
    reviewCount: 19,
    dimensions: { panjang: 45, lebar: 45, tinggi: 165 },
    attributes: {
      finish: "Brushed Brass + Natural Linen",
      frameConstruction: "Solid teak base, brass stem",
    },
    categoryId: "cat-9",
    categoryName: "Pencahayaan",
    room: "Ruang Tamu",
    images: [
      { id: "img-4-1", url: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80", altText: "Lumina Brass Floor Lamp", sortOrder: 0 },
      { id: "img-4-2", url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80", altText: "Lumina Floor Lamp ambient", sortOrder: 1 },
    ],
    variants: [
      { id: "var-4-1", productId: "prod-4", type: "material_kayu", label: "Brass Natural", hexOrSwatch: "#B5A642", priceOffset: 0, stock: 0 },
    ],
    colorSwatches: ["#B5A642"],
    isFeatured: true,
  },
  {
    id: "prod-5",
    name: "Aura Sectional Sofa",
    slug: "aura-sectional-sofa",
    description: "Sofa seksional Aura adalah perwujudan kemewahan bernuansa minimalis. Rangka kayu jati solid dengan bantalan busa multi-layer berlapis performance linen blend memberikan kenyamanan superior. Desain modular memungkinkan konfigurasi yang dapat disesuaikan dengan ruang Anda.",
    price: 24500000,
    material: "Performance Linen Blend",
    status: "Pre-Order",
    statusDetail: "Pre-Order (3 Minggu)",
    rating: 4.9,
    reviewCount: 15,
    dimensions: { panjang: 290, lebar: 180, tinggi: 82 },
    attributes: {
      seatHeight: "44 cm",
      cushionDensity: "Multi-layer HR foam + goose down topper",
      frameConstruction: "Kiln-dried teak, reinforced corner blocks",
    },
    categoryId: "cat-1",
    categoryName: "Sofa & Lounge",
    room: "Ruang Tamu",
    images: [
      { id: "img-5-1", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80", altText: "Aura Sectional Sofa", sortOrder: 0 },
      { id: "img-5-2", url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80", altText: "Aura Sectional detail", sortOrder: 1 },
    ],
    variants: [
      { id: "var-5-1", productId: "prod-5", type: "warna_kain", label: "Oatmeal Linen", hexOrSwatch: "#E8DFD0", priceOffset: 0, stock: 0 },
      { id: "var-5-2", productId: "prod-5", type: "warna_kain", label: "Sage Linen", hexOrSwatch: "#B2BDA0", priceOffset: 500000, stock: 0 },
    ],
    colorSwatches: ["#E8DFD0", "#B2BDA0"],
    isFeatured: false,
  },
  {
    id: "prod-6",
    name: "Sora Curved Sofa",
    slug: "sora-curved-sofa",
    description: "Sora Curved Sofa menghadirkan siluet melengkung yang dramatis namun elegan. Sofa tiga-seater ini dilapisi kain bouclé premium dengan rangka kayu jati yang diperkuat dengan sistem suspensi sinuous spring. Ideal sebagai centerpiece ruang tamu kontemporer.",
    price: 18500000,
    material: "Bouclé Premium, Jati Solid",
    status: "Pre-Order",
    statusDetail: "Pre-Order (3 Minggu)",
    rating: 4.8,
    reviewCount: 22,
    dimensions: { panjang: 240, lebar: 95, tinggi: 78 },
    attributes: {
      seatHeight: "43 cm",
      cushionDensity: "HR foam + sinuous spring system",
      frameConstruction: "Kiln-dried teak frame",
    },
    categoryId: "cat-1",
    categoryName: "Sofa & Lounge",
    room: "Ruang Tamu",
    images: [
      { id: "img-6-1", url: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&q=80", altText: "Sora Curved Sofa", sortOrder: 0 },
    ],
    variants: [
      { id: "var-6-1", productId: "prod-6", type: "warna_kain", label: "Cream Bouclé", hexOrSwatch: "#F5EDE0", priceOffset: 0, stock: 0 },
      { id: "var-6-2", productId: "prod-6", type: "warna_kain", label: "Charcoal Bouclé", hexOrSwatch: "#4A4A4A", priceOffset: 0, stock: 0 },
    ],
    colorSwatches: ["#F5EDE0", "#4A4A4A"],
    isFeatured: false,
  },
  {
    id: "prod-7",
    name: "Nala Weaved Credenza",
    slug: "nala-weaved-credenza",
    description: "Credenza Nala Weaved menampilkan anyaman rotan tangan pada panel pintu, memberikan tekstur organik yang hangat. Rangka kayu jati solid dan kaki berdesain ramping memberikan keseimbangan antara storage praktis dan estetika artisanal.",
    price: 12900000,
    material: "Rotan Alami, Kayu Jati",
    status: "Pre-Order",
    statusDetail: "Pre-Order (3 Minggu)",
    rating: 4.7,
    reviewCount: 14,
    dimensions: { panjang: 180, lebar: 45, tinggi: 75 },
    attributes: {
      finish: "Natural teak oil + clear lacquer",
      frameConstruction: "Jati solid + anyaman rotan manual",
    },
    categoryId: "cat-4",
    categoryName: "Credenza & Konsol",
    room: "Ruang Tamu",
    images: [
      { id: "img-7-1", url: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80", altText: "Nala Weaved Credenza", sortOrder: 0 },
    ],
    variants: [
      { id: "var-7-1", productId: "prod-7", type: "material_kayu", label: "Jati & Rotan", hexOrSwatch: "#8B6914", priceOffset: 0, stock: 0 },
    ],
    colorSwatches: ["#8B6914"],
    isFeatured: false,
  },
  {
    id: "prod-8",
    name: "Veda Lounge Chair",
    slug: "veda-lounge-chair",
    description: "Veda Lounge Chair adalah interpretasi modern dari kursi santai klasik Skandinavia. Rangka kayu ash dengan bantalan linen tebal menciptakan kenyamanan yang mengundang. Desain rendah dan lebar cocok untuk area baca atau sudut relaksasi.",
    price: 5400000,
    material: "Kursi Lounge, Linen",
    status: "Ready Stock",
    rating: 4.6,
    reviewCount: 35,
    dimensions: { panjang: 80, lebar: 85, tinggi: 72 },
    attributes: {
      seatHeight: "38 cm",
      cushionDensity: "High-density foam + linen wrap",
      frameConstruction: "American ash wood",
    },
    categoryId: "cat-2",
    categoryName: "Kursi Aksen",
    room: "Ruang Tamu",
    images: [
      { id: "img-8-1", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80", altText: "Veda Lounge Chair", sortOrder: 0 },
    ],
    variants: [
      { id: "var-8-1", productId: "prod-8", type: "warna_kain", label: "Natural Linen", hexOrSwatch: "#D4C9B5", priceOffset: 0, stock: 15 },
      { id: "var-8-2", productId: "prod-8", type: "warna_kain", label: "Forest Green", hexOrSwatch: "#2D5A3D", priceOffset: 200000, stock: 8 },
    ],
    colorSwatches: ["#D4C9B5", "#2D5A3D"],
    isFeatured: false,
  },
  {
    id: "prod-9",
    name: "Ria Nesting Side Table",
    slug: "ria-nesting-side-table",
    description: "Set meja samping nesting Ria menggabungkan marmer dan kayu jati dalam desain minimalis. Set berisi 2 meja dengan ukuran berbeda yang dapat ditumpuk atau dipisah sesuai kebutuhan. Top marmer putih dengan urat abu-abu halus memberikan sentuhan mewah.",
    price: 3750000,
    material: "Marmer & Jati",
    status: "Ready Stock",
    rating: 4.5,
    reviewCount: 41,
    dimensions: { panjang: 50, lebar: 50, tinggi: 55 },
    attributes: {
      finish: "Marble polished + teak oil",
      frameConstruction: "Jati solid legs + marble top",
    },
    categoryId: "cat-3",
    categoryName: "Meja Kopi & Samping",
    room: "Ruang Tamu",
    images: [
      { id: "img-9-1", url: "https://images.unsplash.com/photo-1532372320978-9f9f12e68e53?w=800&q=80", altText: "Ria Nesting Side Table", sortOrder: 0 },
    ],
    variants: [
      { id: "var-9-1", productId: "prod-9", type: "material_kayu", label: "Jati & White Marble", hexOrSwatch: "#F0EBE3", priceOffset: 0, stock: 12 },
      { id: "var-9-2", productId: "prod-9", type: "material_kayu", label: "Jati & Green Marble", hexOrSwatch: "#6B8C6B", priceOffset: 500000, stock: 5 },
    ],
    colorSwatches: ["#F0EBE3", "#6B8C6B"],
    isFeatured: false,
  },
  {
    id: "prod-10",
    name: "Sora Minimalist Coffee Table",
    slug: "sora-minimalist-coffee-table",
    description: "Meja kopi Sora menampilkan kesederhanaan bentuk yang memukau. Dibuat dari solid ash wood dengan finishing matte alami, meja ini menjadi alas sempurna untuk ritual kopi pagi atau sebagai display untuk buku seni favorit Anda.",
    price: 3200000,
    material: "Solid Jati Premium, Finishing Matte",
    status: "Ready Stock",
    rating: 4.7,
    reviewCount: 55,
    dimensions: { panjang: 110, lebar: 55, tinggi: 40 },
    attributes: {
      finish: "Matte natural oil",
      frameConstruction: "Solid ash, dowel joints",
    },
    categoryId: "cat-3",
    categoryName: "Meja Kopi & Samping",
    room: "Ruang Tamu",
    images: [
      { id: "img-10-1", url: "https://images.unsplash.com/photo-1611967164521-abae8fba4668?w=800&q=80", altText: "Sora Minimalist Coffee Table", sortOrder: 0 },
    ],
    variants: [
      { id: "var-10-1", productId: "prod-10", type: "material_kayu", label: "Ash Natural", hexOrSwatch: "#D4B896", priceOffset: 0, stock: 20 },
      { id: "var-10-2", productId: "prod-10", type: "material_kayu", label: "Walnut Stain", hexOrSwatch: "#5C4033", priceOffset: 250000, stock: 10 },
    ],
    colorSwatches: ["#D4B896", "#5C4033"],
    isFeatured: false,
  },
  {
    id: "prod-11",
    name: "Kala Hand-Woven Wool Rug",
    slug: "kala-hand-woven-wool-rug",
    description: "Karpet wol tenun tangan Kala menghadirkan kehangatan dan tekstur organik ke dalam ruangan. Setiap karpet ditenun secara manual oleh pengrajin lokal menggunakan serat wol Selandia Baru berkualitas tinggi. Pola geometris halus dengan palet warna netral menjadikannya pelengkap sempurna untuk interior Japandi.",
    price: 4100000,
    material: "New Zealand Wool, Hand-Woven",
    status: "Ready Stock",
    rating: 4.8,
    reviewCount: 23,
    dimensions: { panjang: 200, lebar: 150, tinggi: 1 },
    categoryId: "cat-10",
    categoryName: "Dekorasi",
    room: "Ruang Tamu",
    images: [
      { id: "img-11-1", url: "https://images.unsplash.com/photo-1600166898405-da9535204843?w=800&q=80", altText: "Kala Hand-Woven Wool Rug", sortOrder: 0 },
    ],
    variants: [
      { id: "var-11-1", productId: "prod-11", type: "warna_kain", label: "Natural Ivory", hexOrSwatch: "#F5F0E8", priceOffset: 0, stock: 8 },
    ],
    colorSwatches: ["#F5F0E8"],
    isFeatured: false,
  },
  {
    id: "prod-12",
    name: "Aura Arch Floor Lamp",
    slug: "aura-arch-floor-lamp",
    description: "Lampu lantai Aura Arch memiliki desain lengkungan dramatis dengan material kuningan yang disikat dan diffuser kain yang memancarkan cahaya lembut merata. Basis berat menjamin stabilitas sementara ketinggian yang dapat disesuaikan memberikan fleksibilitas penggunaan.",
    price: 2450000,
    material: "Kuningan disikat (Brushed Brass), Diffuser kain",
    status: "Ready Stock",
    rating: 4.5,
    reviewCount: 31,
    dimensions: { panjang: 40, lebar: 40, tinggi: 180 },
    categoryId: "cat-9",
    categoryName: "Pencahayaan",
    room: "Pencahayaan",
    images: [
      { id: "img-12-1", url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80", altText: "Aura Arch Floor Lamp", sortOrder: 0 },
    ],
    variants: [
      { id: "var-12-1", productId: "prod-12", type: "material_kayu", label: "Brushed Brass", hexOrSwatch: "#D4A937", priceOffset: 0, stock: 10 },
      { id: "var-12-2", productId: "prod-12", type: "material_kayu", label: "Matte Black", hexOrSwatch: "#2C2C2C", priceOffset: 0, stock: 7 },
    ],
    colorSwatches: ["#D4A937", "#2C2C2C"],
    isFeatured: false,
  },
  {
    id: "prod-13",
    name: "Nara Upholstered Bed",
    slug: "nara-upholstered-bed",
    description: "Tempat tidur Nara menampilkan headboard berlapis kain yang tinggi dengan rangka kayu mahoni premium. Sandaran bertekstur vertikal memberikan dimensi visual yang menarik sekaligus menambah kenyamanan saat bersandar untuk membaca. Kain tahan noda menjadikannya pilihan praktis untuk kamar tidur.",
    price: 8900000,
    material: "Kayu Mahoni, Kain Tahan Noda",
    status: "Ready Stock",
    rating: 4.9,
    reviewCount: 18,
    dimensions: { panjang: 220, lebar: 180, tinggi: 120 },
    categoryId: "cat-5",
    categoryName: "Tempat Tidur",
    room: "Kamar Tidur",
    images: [
      { id: "img-13-1", url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80", altText: "Nara Upholstered Bed", sortOrder: 0 },
    ],
    variants: [
      { id: "var-13-1", productId: "prod-13", type: "warna_kain", label: "Oatmeal Linen", hexOrSwatch: "#E8DFD0", priceOffset: 0, stock: 6 },
      { id: "var-13-2", productId: "prod-13", type: "warna_kain", label: "Navy Velvet", hexOrSwatch: "#1B2A4A", priceOffset: 500000, stock: 4 },
    ],
    colorSwatches: ["#E8DFD0", "#1B2A4A"],
    isFeatured: false,
  },
  {
    id: "prod-14",
    name: "Solace Dining Table",
    slug: "solace-dining-table",
    description: "Meja makan Solace dibuat dari kayu walnut Amerika pilihan dengan permukaan yang mempertahankan keindahan serat alami. Kaki berbentuk trapezoid memberikan stabilitas superior sekaligus estetika yang striking. Cukup untuk 6-8 orang.",
    price: 11000000,
    material: "American Walnut, Finishing Matte",
    status: "Ready Stock",
    rating: 4.8,
    reviewCount: 12,
    dimensions: { panjang: 200, lebar: 90, tinggi: 75 },
    categoryId: "cat-6",
    categoryName: "Meja Makan",
    room: "Ruang Makan",
    images: [
      { id: "img-14-1", url: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80", altText: "Solace Dining Table", sortOrder: 0 },
    ],
    variants: [
      { id: "var-14-1", productId: "prod-14", type: "material_kayu", label: "American Walnut", hexOrSwatch: "#5C4033", priceOffset: 0, stock: 5 },
    ],
    colorSwatches: ["#5C4033"],
    isFeatured: false,
  },
  {
    id: "prod-15",
    name: "Senja Floor Lamp",
    slug: "senja-floor-lamp",
    description: "Lampu lantai Senja terinspirasi dari senja tropis Indonesia. Kombinasi kayu jati dan shade kain katun organik menciptakan pencahayaan hangat yang menenangkan. Cocok untuk sudut baca atau sebagai ambient light di ruang tidur.",
    price: 2500000,
    material: "Kayu Jati, Katun Organik",
    status: "Ready Stock",
    rating: 4.4,
    reviewCount: 28,
    dimensions: { panjang: 35, lebar: 35, tinggi: 155 },
    categoryId: "cat-9",
    categoryName: "Pencahayaan",
    room: "Pencahayaan",
    images: [
      { id: "img-15-1", url: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80", altText: "Senja Floor Lamp", sortOrder: 0 },
    ],
    variants: [
      { id: "var-15-1", productId: "prod-15", type: "material_kayu", label: "Teak Natural", hexOrSwatch: "#8B6914", priceOffset: 0, stock: 15 },
    ],
    colorSwatches: ["#8B6914"],
    isFeatured: false,
  },
  {
    id: "prod-16",
    name: "Lumina Velvet Sofa",
    slug: "lumina-velvet-sofa",
    description: "Sofa Lumina Velvet menghadirkan kemewahan klasik dalam desain kontemporer. Upholsteri velvet premium dengan rangka kayu jati kiln-dried memberikan kesan mewah namun tahan lama. Bantalan reversible memastikan umur pemakaian yang panjang.",
    price: 14500000,
    material: "Velvet Premium, Jati Solid",
    status: "Ready Stock",
    rating: 4.9,
    reviewCount: 9,
    dimensions: { panjang: 220, lebar: 90, tinggi: 80 },
    categoryId: "cat-1",
    categoryName: "Sofa & Lounge",
    room: "Ruang Tamu",
    images: [
      { id: "img-16-1", url: "https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=800&q=80", altText: "Lumina Velvet Sofa", sortOrder: 0 },
    ],
    variants: [
      { id: "var-16-1", productId: "prod-16", type: "warna_kain", label: "Emerald Velvet", hexOrSwatch: "#2D6B4E", priceOffset: 0, stock: 3 },
      { id: "var-16-2", productId: "prod-16", type: "warna_kain", label: "Rust Velvet", hexOrSwatch: "#A0522D", priceOffset: 0, stock: 4 },
    ],
    colorSwatches: ["#2D6B4E", "#A0522D"],
    isFeatured: false,
  },
  {
    id: "prod-17",
    name: "Aurelia Lounge Chair",
    slug: "aurelia-lounge-chair",
    description: "Aurelia Lounge Chair mengkombinasikan desain mid-century Skandinavia dengan material tropis Indonesia. Rangka kayu jati lengkung dengan anyaman webbing rotan pada sandaran memberikan kenyamanan dan estetika yang unik.",
    price: 6800000,
    material: "Kayu Jati, Rotan Webbing, Linen",
    status: "Ready Stock",
    rating: 4.7,
    reviewCount: 21,
    dimensions: { panjang: 78, lebar: 82, tinggi: 76 },
    categoryId: "cat-2",
    categoryName: "Kursi Aksen",
    room: "Ruang Tamu",
    images: [
      { id: "img-17-1", url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80", altText: "Aurelia Lounge Chair", sortOrder: 0 },
    ],
    variants: [
      { id: "var-17-1", productId: "prod-17", type: "material_kayu", label: "Teak & Natural Rattan", hexOrSwatch: "#C8A951", priceOffset: 0, stock: 9 },
    ],
    colorSwatches: ["#C8A951"],
    isFeatured: false,
  },
  {
    id: "prod-18",
    name: "Kinu Bedside Table",
    slug: "kinu-bedside-table",
    description: "Meja samping tempat tidur Kinu dibuat dari kayu oak solid dengan desain minimalis. Laci tanpa handle menggunakan mekanisme push-open untuk tampilan yang bersih. Cocok dipasangkan dengan tempat tidur Nara atau sebagai standalone accent table.",
    price: 1950000,
    material: "Kayu Oak Solid",
    status: "Ready Stock",
    rating: 4.6,
    reviewCount: 44,
    dimensions: { panjang: 45, lebar: 40, tinggi: 55 },
    categoryId: "cat-3",
    categoryName: "Meja Kopi & Samping",
    room: "Kamar Tidur",
    images: [
      { id: "img-18-1", url: "https://images.unsplash.com/photo-1532372320978-9f9f12e68e53?w=800&q=80", altText: "Kinu Bedside Table", sortOrder: 0 },
    ],
    variants: [
      { id: "var-18-1", productId: "prod-18", type: "material_kayu", label: "Oak Natural", hexOrSwatch: "#C4A35A", priceOffset: 0, stock: 18 },
    ],
    colorSwatches: ["#C4A35A"],
    isFeatured: false,
  },
  {
    id: "prod-19",
    name: "Sora Ceramic Table Lamp",
    slug: "sora-ceramic-table-lamp",
    description: "Lampu meja keramik Sora dibuat dengan teknik raku tradisional Jepang, menghasilkan glaze yang unik pada setiap unit. Base keramik dengan shade linen organik menciptakan pencahayaan ambient yang hangat dan menenangkan.",
    price: 1450000,
    material: "Keramik Raku, Linen",
    status: "Ready Stock",
    rating: 4.3,
    reviewCount: 37,
    dimensions: { panjang: 25, lebar: 25, tinggi: 45 },
    categoryId: "cat-9",
    categoryName: "Pencahayaan",
    room: "Pencahayaan",
    images: [
      { id: "img-19-1", url: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80", altText: "Sora Ceramic Table Lamp", sortOrder: 0 },
    ],
    variants: [
      { id: "var-19-1", productId: "prod-19", type: "warna_kain", label: "Matte Sand", hexOrSwatch: "#C9B99A", priceOffset: 0, stock: 14 },
    ],
    colorSwatches: ["#C9B99A"],
    isFeatured: false,
  },
  {
    id: "prod-20",
    name: "Hana Woven Wool Rug",
    slug: "hana-woven-wool-rug",
    description: "Karpet tenun Hana memadukan wol dan serat katun dalam pola abstrak yang terinspirasi dari alam. Dibuat secara handmade dengan teknik flatweave yang menghasilkan tekstur tipis dan rata, ideal untuk ruang makan atau ruang tamu modern.",
    price: 2800000,
    material: "Wool & Katun Blend, Handmade",
    status: "Ready Stock",
    rating: 4.5,
    reviewCount: 19,
    dimensions: { panjang: 180, lebar: 120, tinggi: 1 },
    categoryId: "cat-10",
    categoryName: "Dekorasi",
    room: "Dekorasi",
    images: [
      { id: "img-20-1", url: "https://images.unsplash.com/photo-1600166898405-da9535204843?w=800&q=80", altText: "Hana Woven Wool Rug", sortOrder: 0 },
    ],
    variants: [
      { id: "var-20-1", productId: "prod-20", type: "warna_kain", label: "Earth Tone", hexOrSwatch: "#B5986C", priceOffset: 0, stock: 11 },
    ],
    colorSwatches: ["#B5986C"],
    isFeatured: false,
  },
  {
    id: "prod-21",
    name: "Komorebi Ceramic Table Lamp",
    slug: "komorebi-ceramic-table-lamp",
    description: "Terinspirasi dari fenomena 'komorebi' (sinar matahari yang menembus dedaunan), lampu meja ini memancarkan cahaya lembut melalui shade keramik berlubang halus. Setiap lubang ditusuk secara manual, menciptakan pola cahaya yang menyerupai bayangan daun.",
    price: 4150000,
    material: "Keramik Artisanal, Matte Sand",
    status: "Ready Stock",
    rating: 4.7,
    reviewCount: 16,
    dimensions: { panjang: 30, lebar: 30, tinggi: 48 },
    categoryId: "cat-9",
    categoryName: "Pencahayaan",
    room: "Pencahayaan",
    images: [
      { id: "img-21-1", url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80", altText: "Komorebi Ceramic Table Lamp", sortOrder: 0 },
    ],
    variants: [
      { id: "var-21-1", productId: "prod-21", type: "warna_kain", label: "Matte Sand", hexOrSwatch: "#C9B99A", priceOffset: 0, stock: 8 },
    ],
    colorSwatches: ["#C9B99A"],
    isFeatured: false,
  },
  {
    id: "prod-22",
    name: "Sora Coffee Table",
    slug: "sora-coffee-table",
    description: "Meja kopi Sora dengan sudut membulat elegan, dibuat dari kayu oak Jerman dengan finishing natural matte. Desain low-profile dengan kaki tapered menghadirkan estetika Japandi yang tenang dan fungsional.",
    price: 3200000,
    material: "Kayu Oak Jerman, Finishing Natural Matte",
    status: "Terbatas",
    rating: 4.6,
    reviewCount: 29,
    dimensions: { panjang: 100, lebar: 60, tinggi: 38 },
    categoryId: "cat-3",
    categoryName: "Meja Kopi & Samping",
    room: "Ruang Tamu",
    images: [
      { id: "img-22-1", url: "https://images.unsplash.com/photo-1634712282287-14ed57b9cc89?w=800&q=80", altText: "Sora Coffee Table", sortOrder: 0 },
    ],
    variants: [
      { id: "var-22-1", productId: "prod-22", type: "material_kayu", label: "Oak Natural", hexOrSwatch: "#C4A35A", priceOffset: 0, stock: 2 },
    ],
    colorSwatches: ["#C4A35A"],
    isFeatured: false,
  },
  {
    id: "prod-23",
    name: "Aura Lounge Chair",
    slug: "aura-lounge-chair",
    description: "Aura Lounge Chair dibuat untuk kenyamanan tanpa kompromi. Rangka natural oak dengan bantalan linen organic yang tebal memberikan dukungan ergonomis optimal. Ideal sebagai kursi baca atau sudut relaksasi.",
    price: 14500000,
    material: "Natural Oak, Oatmeal Linen",
    status: "Bestseller",
    statusDetail: "Bestseller",
    rating: 4.9,
    reviewCount: 67,
    dimensions: { panjang: 85, lebar: 90, tinggi: 78 },
    categoryId: "cat-2",
    categoryName: "Kursi Aksen",
    room: "Ruang Tamu",
    images: [
      { id: "img-23-1", url: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80", altText: "Aura Lounge Chair", sortOrder: 0 },
    ],
    variants: [
      { id: "var-23-1", productId: "prod-23", type: "warna_kain", label: "Oatmeal Linen", hexOrSwatch: "#E8DFD0", priceOffset: 0, stock: 5 },
    ],
    colorSwatches: ["#E8DFD0"],
    isFeatured: false,
  },
];

// ─── Testimonials ────────────────────────────────────────────────────────────
export interface Testimonial {
  id: string;
  name: string;
  location: string;
  rating: number;
  quote: string;
  avatarUrl?: string;
}

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Sarah Prameswari",
    location: "Kebayoran Baru, Jakarta",
    rating: 5,
    quote: "Kualitas kayu jatinya sangat terasa kokoh namun memiliki finishing yang halus lembut. Benar-benar mengubah suasana ruang tamu kami menjadi seperti galeri seni.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
  },
  {
    id: "test-2",
    name: "Reza Gunawan",
    location: "BSD City, Tangerang",
    rating: 5,
    quote: "Pelayanan pengiriman dan instalasi sangat profesional. Sofa linen organiknya sangat nyaman dan warnanya pas dengan konsep Japandi rumah kami.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
  {
    id: "test-3",
    name: "Dian Sustrowahyuni",
    location: "Menteng, Jakarta",
    rating: 5,
    quote: "Sudah pembelian kedua kalinya di Maison Lumina. Meja makannya menjadi pusat perhatian setiap kali ada tamu yang datang berkunjung.",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  },
];

// ─── Room images (for Shop by Room / hotspot section) ────────────────────────
export const roomImages: Record<string, { imageUrl: string; altText: string }> = {
  "Ruang Tamu": {
    imageUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80",
    altText: "Inspirasi Ruang Tamu Japandi",
  },
  "Kamar Tidur": {
    imageUrl: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=80",
    altText: "Inspirasi Kamar Tidur Zen",
  },
  "Ruang Makan": {
    imageUrl: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1200&q=80",
    altText: "Inspirasi Ruang Makan Minimalis",
  },
  "Ruang Kerja": {
    imageUrl: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=1200&q=80",
    altText: "Inspirasi Ruang Kerja Produktif",
  },
};

// ─── Mock User Profile ───────────────────────────────────────────────────────
export const mockUserProfile: UserProfile = {
  id: "user-1",
  name: "Victoria Alithea",
  email: "victoria.alithea@maisonlumina.client",
  tier: "VIP",
  loyaltyPoints: 2450,
  avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
  addresses: [
    {
      id: "addr-1",
      recipient: "Dian Sastrowardoyo",
      phone: "+62 812-3456-7890",
      fullAddress: "Jl. Senopati Raya No. 42, Kebayoran Baru, Jakarta Selatan 12190",
      notes: "Rumah warna putih pagar hitam, titip di ruang tamu lantai 1",
      isDefault: true,
    },
  ],
};

// ─── Mock Order History ──────────────────────────────────────────────────────
export const mockOrders: Order[] = [
  {
    id: "order-1",
    orderNumber: "#ML-88492",
    userId: "user-1",
    status: "Sedang Dikirim",
    subtotal: 14500000,
    shippingFee: 0,
    installFee: 0,
    tax: 0,
    total: 14500000,
    paymentMethod: "Transfer Bank (BCA)",
    paymentStatus: "Lunas",
    shippingDate: "2024-10-28",
    shippingSlot: "Selasa, 28 Okt 2024 (Pukul 10:00 - 13:00 WIB)",
    recipientName: "Dian Sastrowardoyo",
    recipientPhone: "+62 812-3456-7890",
    shippingAddress: "Jl. Senopati Raya No. 42, Kebayoran Baru, Jakarta Selatan 12190",
    deliveryNotes: "Rumah warna putih pagar hitam, titip di ruang tamu lantai 1",
    items: [
      {
        id: "oi-1",
        productId: "prod-23",
        product: products.find(p => p.id === "prod-23")!,
        variantLabel: "Natural Oak / Oatmeal Linen",
        qty: 1,
        priceAtOrder: 14500000,
      },
    ],
    createdAt: "2024-10-24T14:32:00Z",
  },
  {
    id: "order-2",
    orderNumber: "#ML-87102",
    userId: "user-1",
    status: "Selesai",
    subtotal: 28200000,
    shippingFee: 0,
    installFee: 0,
    tax: 0,
    total: 28200000,
    paymentMethod: "Transfer Bank (BCA)",
    paymentStatus: "Lunas",
    shippingDate: "2024-09-12",
    recipientName: "Dian Sastrowardoyo",
    recipientPhone: "+62 812-3456-7890",
    shippingAddress: "Jl. Senopati Raya No. 42, Kebayoran Baru, Jakarta Selatan 12190",
    items: [
      {
        id: "oi-2",
        productId: "prod-14",
        product: products.find(p => p.id === "prod-14")!,
        variantLabel: "American Walnut",
        qty: 1,
        priceAtOrder: 28200000,
      },
    ],
    createdAt: "2024-09-08T10:00:00Z",
  },
  {
    id: "order-3",
    orderNumber: "#ML-85210",
    userId: "user-1",
    status: "Selesai",
    subtotal: 4150000,
    shippingFee: 0,
    installFee: 0,
    tax: 0,
    total: 4150000,
    paymentMethod: "QRIS / E-Wallet",
    paymentStatus: "Lunas",
    shippingDate: "2024-08-04",
    recipientName: "Dian Sastrowardoyo",
    recipientPhone: "+62 812-3456-7890",
    shippingAddress: "Jl. Senopati Raya No. 42, Kebayoran Baru, Jakarta Selatan 12190",
    items: [
      {
        id: "oi-3",
        productId: "prod-21",
        product: products.find(p => p.id === "prod-21")!,
        variantLabel: "Matte Sand",
        qty: 2,
        priceAtOrder: 4150000,
      },
    ],
    createdAt: "2024-07-30T09:00:00Z",
  },
];

// ─── Filter options ──────────────────────────────────────────────────────────
export const materialOptions = [
  { label: "Kayu Jati Solid", count: 24 },
  { label: "Rotan Alami", count: 8 },
  { label: "Linen Premium", count: 12 },
  { label: "Bouclé Fabric", count: 6 },
];

export const colorSwatchOptions = [
  { label: "Dark Walnut", hex: "#5C4033" },
  { label: "Espresso", hex: "#3C2415" },
  { label: "Natural Oak", hex: "#C4A35A" },
  { label: "Honey Teak", hex: "#C8A951" },
  { label: "Cream", hex: "#F5EDE0" },
];
